### ISSUE TITLE
Compare a given list of evaluations

### ISSUE THREAD

**Issue by HackerFoo** [SymbiFlow/FPGA-Tool-Performance-Visualization-Library#7]
Given a list of evaluations, produce series of tables (or rows) showing metrics with respect to the first eval e.g.

| Eval | Placement Time | Routing Time | CPD |
|-|-|-|-|
| 1 | 100s | 200s | 18ns |
| 2 | 50s (2x) | 150 (1.3x) | 18ns (1x) |
| 3 | 25s (4x) | 100 (2x) | 15ns (1.2x) |

**Comment by TypingKoala** [comment]
This improvement may need #9 for filtering evaluations into a single row so that multiple can be compared.
